"use client";

import { useState, useEffect } from "react";
import { MessageCircle, User, Bot, Calendar, Phone, Mail, Loader2, ArrowRight, MessageSquareDashed, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";

interface Message {
    id: string;
    role: "user" | "bot";
    content: string;
    createdAt: string;
}

interface ChatSession {
    id: string;
    guestName: string | null;
    email: string | null;
    phone: string | null;
    createdAt: string;
    messages: Message[];
}

export default function AdminChatbotLogs() {
    const [sessions, setSessions] = useState<ChatSession[]>([]);
    const [loading, setLoading] = useState(true);
    const [selectedSession, setSelectedSession] = useState<string | null>(null);
    const [deleting, setDeleting] = useState<string | null>(null);

    useEffect(() => {
        fetchSessions();
    }, []);

    const fetchSessions = () => {
        setLoading(true);
        fetch("/api/admin/chatbot")
            .then((r) => r.json())
            .then(setSessions)
            .finally(() => setLoading(false));
    };

    const handleDelete = async (e: React.MouseEvent, id: string) => {
        e.stopPropagation();
        if (!confirm("Are you sure you want to delete this chat session?")) return;

        setDeleting(id);
        try {
            const res = await fetch(`/api/admin/chatbot?id=${id}`, { method: "DELETE" });
            if (res.ok) {
                toast.success("Chat session deleted");
                setSessions(sessions.filter(s => s.id !== id));
                if (selectedSession === id) setSelectedSession(null);
            } else {
                toast.error("Failed to delete chat session");
            }
        } catch (error) {
            toast.error("An error occurred");
        } finally {
            setDeleting(null);
        }
    };

    const selectedData = sessions.find((s) => s.id === selectedSession);

    if (loading) return <div className="flex items-center justify-center py-20"><Loader2 className="animate-spin text-gold-accent" /></div>;

    return (
        <div className="space-y-6 h-[calc(100vh-120px)] flex flex-col">
            <div>
                <h1 className="text-2xl font-bold text-navy-dark">AI Chat Leads</h1>
                <p className="text-sm text-muted-foreground">Review leads generated by Little Adu.</p>
            </div>

            <div className="flex-1 flex gap-6 overflow-hidden">
                {/* Session List */}
                <div className="w-80 bg-white border border-navy-primary/5 rounded-2xl overflow-y-auto shadow-sm flex flex-col">
                    <div className="p-4 border-b bg-cream-bg/20 font-bold text-navy-primary text-sm uppercase tracking-wider flex justify-between items-center">
                        <span>Recent Leads</span>
                        <Badge variant="outline" className="text-[10px]">{sessions.length}</Badge>
                    </div>
                    {sessions.map((s) => (
                        <div
                            key={s.id}
                            role="button"
                            tabIndex={0}
                            onClick={() => setSelectedSession(s.id)}
                            onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') setSelectedSession(s.id); }}
                            className={`w-full text-left p-4 border-b hover:bg-gold-accent/5 transition-colors group relative cursor-pointer ${selectedSession === s.id ? "bg-gold-accent/10 border-l-4 border-l-gold-accent" : "border-navy-primary/5"}`}
                        >
                            <div className="flex items-center gap-3 mb-2">
                                <div className="w-10 h-10 rounded-full bg-navy-primary/10 flex items-center justify-center text-navy-primary font-bold">
                                    {s.guestName ? s.guestName.charAt(0).toUpperCase() : <User size={16} />}
                                </div>
                                <div className="flex-1 overflow-hidden">
                                    <span className="font-bold text-sm text-navy-dark truncate block">{s.guestName || "Guest User"}</span>
                                    <span className="text-xs flex items-center gap-1 text-muted-foreground"><Phone className="w-3 h-3" /> {s.phone || 'N/A'}</span>
                                </div>
                            </div>
                            <div className="flex items-center justify-between">
                                <span className="text-[10px] text-muted-foreground shrink-0 flex items-center gap-1">
                                    <Calendar className="w-3 h-3" /> {new Date(s.createdAt).toLocaleDateString()}
                                </span>
                                <Button
                                    variant="ghost"
                                    size="icon"
                                    onClick={(e) => handleDelete(e, s.id)}
                                    disabled={deleting === s.id}
                                    className="h-6 w-6 text-muted-foreground hover:text-red-500 hover:bg-red-50"
                                >
                                    {deleting === s.id ? <Loader2 className="w-3 h-3 animate-spin" /> : <Trash2 className="w-3 h-3" />}
                                </Button>
                            </div>
                        </div>
                    ))}
                    {sessions.length === 0 && (
                        <div className="p-10 text-center text-muted-foreground flex-1 flex flex-col items-center justify-center">
                            <MessageSquareDashed className="w-10 h-10 mx-auto mb-3 opacity-20" />
                            <p className="text-sm italic">No chat leads generated yet.</p>
                        </div>
                    )}
                </div>

                {/* Lead Contact Info & Chat Detail */}
                <div className="flex-1 bg-white border border-navy-primary/5 rounded-2xl shadow-sm flex flex-col overflow-hidden">
                    {selectedData ? (
                        <>
                            {/* Prominent Lead Header */}
                            <div className="p-6 border-b bg-gradient-to-r from-navy-dark to-navy-primary text-white">
                                <div className="flex justify-between items-start">
                                    <div className="flex items-center gap-4">
                                        <div className="w-14 h-14 rounded-2xl bg-white/10 flex items-center justify-center border border-white/20">
                                            <User className="w-7 h-7 text-gold-accent" />
                                        </div>
                                        <div>
                                            <h2 className="text-2xl font-bold">{selectedData.guestName || "Anonymous Lead"}</h2>
                                            <div className="flex flex-wrap items-center gap-x-6 gap-y-2 mt-2">
                                                <div className="flex items-center gap-2 text-sm text-white/90">
                                                    <Phone className="w-4 h-4 text-gold-accent" />
                                                    <a href={`tel:${selectedData.phone}`} className="hover:underline hover:text-gold-accent transition-colors">{selectedData.phone || 'No phone provided'}</a>
                                                </div>
                                                <div className="flex items-center gap-2 text-sm text-white/90">
                                                    <Calendar className="w-4 h-4 text-gold-accent" />
                                                    <span>Created {new Date(selectedData.createdAt).toLocaleString()}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="flex gap-2">
                                        <Button variant="outline" size="sm" className="bg-white/10 border-white/20 text-white hover:bg-white hover:text-navy-dark" onClick={(e) => handleDelete(e, selectedData.id)}>
                                            <Trash2 className="w-4 h-4 mr-2" /> Delete Lead
                                        </Button>
                                    </div>
                                </div>
                            </div>

                            {/* Chat Transcript Section */}
                            <div className="px-6 py-3 border-b bg-cream-bg/30 text-xs font-bold text-navy-primary uppercase tracking-wider flex items-center gap-2">
                                <MessageCircle className="w-4 h-4" /> AI Interaction Transcript
                            </div>

                            <div className="flex-1 overflow-y-auto p-6 space-y-4 bg-gray-50/50">
                                {selectedData.messages.length === 0 ? (
                                    <div className="text-center text-muted-foreground py-10 italic text-sm">No follow-up conversation occurred for this lead.</div>
                                ) : (
                                    selectedData.messages.map((m) => (
                                        <div key={m.id} className={`flex gap-3 ${m.role === "user" ? "justify-end" : "justify-start"}`}>
                                            <div className={`max-w-[75%] p-4 rounded-2xl text-sm ${m.role === "user" ? "bg-navy-primary text-white rounded-tr-none shadow-md" : "bg-white border text-gray-800 shadow-sm rounded-tl-none border-gray-100"}`}>
                                                <p className="whitespace-pre-wrap">{m.content}</p>
                                                <span className={`text-[10px] block mt-2 opacity-60 ${m.role === "user" ? "text-right" : "text-left"}`}>
                                                    {new Date(m.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} • {m.role === "user" ? "Lead" : "Little Adu AI"}
                                                </span>
                                            </div>
                                        </div>
                                    ))
                                )}
                            </div>
                        </>
                    ) : (
                        <div className="flex-1 flex flex-col items-center justify-center text-muted-foreground p-10 text-center bg-gray-50/30">
                            <div className="w-20 h-20 rounded-full bg-cream-bg flex items-center justify-center mb-6 shadow-inner">
                                <User className="w-10 h-10 text-gold-accent opacity-50" />
                            </div>
                            <h3 className="text-xl font-bold text-navy-primary mb-2">Select a Lead</h3>
                            <p className="max-w-sm text-sm opacity-80">Choose a lead from the sidebar to view their complete contact details and browse their AI chatbot inquiry transcript.</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
